#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx tsc --pretty --noEmit && npx eslint . --ext ts --ext tsx --ext js . && npx prettier --check . 

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am committing this now. ✅✅✅✅'
